# Generated by Django 3.2.1 on 2021-05-05 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pizzaDropdown',
            fields=[
                ('sno', models.AutoField(db_column='sno', primary_key=True, serialize=False)),
                ('pid', models.IntegerField(db_column='pid')),
                ('feild', models.CharField(db_column='feild', max_length=500)),
                ('value', models.CharField(db_column='value', max_length=550)),
                ('is_delete', models.IntegerField(db_column='is_delete')),
                ('is_edit', models.IntegerField(db_column='is_edit')),
            ],
        ),
        migrations.CreateModel(
            name='pizzaCreated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_edit', models.IntegerField(db_column='is_edit')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pizzasize', to='pizzaApp.pizzadropdown')),
                ('toppings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pizzatoppings', to='pizzaApp.pizzadropdown')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pizzatype', to='pizzaApp.pizzadropdown')),
            ],
        ),
    ]
