# Generated by Django 3.2.1 on 2021-05-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizzacreated',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pizzadropdown',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='pizzacreated',
            name='is_edit',
            field=models.IntegerField(db_column='is_edit', default=0),
        ),
        migrations.AlterField(
            model_name='pizzadropdown',
            name='is_delete',
            field=models.IntegerField(db_column='is_delete', default=0),
        ),
        migrations.AlterField(
            model_name='pizzadropdown',
            name='is_edit',
            field=models.IntegerField(db_column='is_edit', default=0),
        ),
        migrations.AlterModelTable(
            name='pizzacreated',
            table='Pizzacreated',
        ),
        migrations.AlterModelTable(
            name='pizzadropdown',
            table='Pizzadropdown',
        ),
    ]
